### ISSUE TITLE
what mean for 8000 and [num_iter] ?

### ISSUE THREAD

**Issue by xsk0206** [shreya-28/Secure-ML#2]
hello, thanks for sharing, I have successfully run the experiment. But I still have a question:
`./secure_ML 1 8000 [num_iter]`   
what mean for `8000` and `[num_iter]` ?

**Comment by shreya-28** [comment]
Hey, 8000 is the port number for communication and num_iter is the number of iterations you wish to run for the algorithm. Hope this helps!
